import type { Metadata } from "next";
import {Arvo,Lexend_Deca} from "next/font/google";
import "./globals.css";

const arvo = Arvo({
  weight: ["400","700"],
  subsets: ["latin"],
});

const lexenddeca = Lexend_Deca({
  weight: ["100","200","300","400","500","600","700","800","900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by portfolio",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${arvo} ${lexenddeca}antialiased`}
      >
        {children}
      </body>
    </html>      
  );
}
